name: nbterm-dev
channels:
    - conda-forge
dependencies:
    - pip
    - prompt_toolkit >=3
    - typer
    - pygments
    - rich
    - flake8
    - black
    - pip:
      - git+https://github.com/davidbrochart/kernel_driver.git#egg=kernel_driver
